// SPDX-FileCopyrightText: 2026 SPHARX Ltd.
// SPDX-License-Identifier: Apache-2.0
/**
 * @file error.h
 * @brief 错误处理兼容层
 * 
 * 本文件是 agentos/commons/utils/error 的兼容层，提供向后兼容的 API。
 * 新代码应直接使用 #include <error.h>
 * 
 * @see agentos/commons/utils/error/include/error.h
 */

#ifndef AGENTOS_DAEMON_COMMON_ERROR_H
#define AGENTOS_DAEMON_COMMON_ERROR_H

/* 包含 commons 的统一错误处理框架 */
/* 使用相对路径避免 include 搜索找到 daemon 自身的 error.h */
#include "../../../commons/utils/error/include/error.h"

#ifndef AGENTOS_OK
#define AGENTOS_OK                      0
#endif

/* ==================== 兼容性别名 ==================== */

/* 旧的错误码名称映射到新的名称 */
#ifndef AGENTOS_SUCCESS
#define AGENTOS_SUCCESS                    AGENTOS_OK
#endif
#define AGENTOS_ERROR_UNKNOWN              AGENTOS_ERR_UNKNOWN
#define AGENTOS_ERROR_OUT_OF_MEMORY        AGENTOS_ERR_OUT_OF_MEMORY
#define AGENTOS_ERROR_INVALID_PARAMETER    AGENTOS_ERR_INVALID_PARAM
#define AGENTOS_ERROR_NULL_POINTER         AGENTOS_ERR_NULL_POINTER
#define AGENTOS_ERROR_BUFFER_TOO_SMALL     AGENTOS_ERR_BUFFER_TOO_SMALL
#define AGENTOS_ERROR_NOT_FOUND            AGENTOS_ERR_NOT_FOUND
#define AGENTOS_ERROR_ALREADY_EXISTS       AGENTOS_ERR_ALREADY_EXISTS
#define AGENTOS_ERROR_TIMEOUT              AGENTOS_ERR_TIMEOUT
#define AGENTOS_ERROR_NOT_SUPPORTED        AGENTOS_ERR_NOT_SUPPORTED
#define AGENTOS_ERROR_PERMISSION_DENIED    AGENTOS_ERR_PERMISSION_DENIED
#define AGENTOS_ERROR_IO_ERROR             AGENTOS_ERR_IO
#define AGENTOS_ERROR_PARSE_ERROR          AGENTOS_ERR_PARSE_ERROR
#define AGENTOS_ERROR_STATE_ERROR          AGENTOS_ERR_STATE_ERROR
#define AGENTOS_ERROR_OVERFLOW             AGENTOS_ERR_OVERFLOW
#define AGENTOS_ERROR_UNDERFLOW            AGENTOS_ERR_UNDERFLOW
#define AGENTOS_ERROR_BUSY                 AGENTOS_ERR_BUSY
#define AGENTOS_ERROR_CORRUPTED_DATA       AGENTOS_ERR_MEM_CORRUPT
#define AGENTOS_ERROR_INTERNAL             AGENTOS_ERR_UNKNOWN

/* 核心循环错误码兼容 */
#define AGENTOS_ERROR_LOOP_BASE            AGENTOS_ERR_KERN_BASE
#define AGENTOS_ERROR_LOOP_CREATE_FAILED   AGENTOS_ERR_KERN_TASK
#define AGENTOS_ERROR_LOOP_RUN_FAILED      AGENTOS_ERR_KERN_TASK
#define AGENTOS_ERROR_LOOP_STOP_FAILED     AGENTOS_ERR_KERN_TASK
#define AGENTOS_ERROR_TASK_SUBMIT_FAILED   AGENTOS_ERR_KERN_TASK
#define AGENTOS_ERROR_TASK_WAIT_FAILED     AGENTOS_ERR_KERN_TASK

/* 服务层错误码兼容 */
#define AGENTOS_ERROR_SERVICE_BASE         AGENTOS_ERR_SVC_BASE
#define AGENTOS_ERROR_SERVICE_NOT_READY    AGENTOS_ERR_SVC_NOT_READY
#define AGENTOS_ERROR_SERVICE_BUSY         AGENTOS_ERR_SVC_BUSY
#define AGENTOS_ERROR_SERVICE_STOPPED      AGENTOS_ERR_SVC_STOPPED
#define AGENTOS_ERROR_SERVICE_CONFIG       AGENTOS_ERR_SVC_CONFIG

/* IPC 错误码兼容 */
#define AGENTOS_ERROR_IPC_BASE             AGENTOS_ERR_KERN_BASE
#define AGENTOS_ERROR_IPC_CONNECT          AGENTOS_ERR_KERN_IPC
#define AGENTOS_ERROR_IPC_DISCONNECT       AGENTOS_ERR_KERN_IPC
#define AGENTOS_ERROR_IPC_TIMEOUT          AGENTOS_ERR_TIMEOUT
#define AGENTOS_ERROR_IPC_INVALID_MSG      AGENTOS_ERR_KERN_IPC
#define AGENTOS_ERROR_IPC_BUFFER_FULL      AGENTOS_ERR_BUFFER_TOO_SMALL

/* LLM 服务错误码兼容 */
#define AGENTOS_ERROR_LLM_BASE             AGENTOS_ERR_LLM_BASE
#define AGENTOS_ERROR_LLM_NO_PROVIDER      AGENTOS_ERR_LLM_NO_PROVIDER
#define AGENTOS_ERROR_LLM_PROVIDER_FAIL    AGENTOS_ERR_LLM_PROVIDER_FAIL
#define AGENTOS_ERROR_LLM_RATE_LIMIT       AGENTOS_ERR_LLM_RATE_LIMIT
#define AGENTOS_ERROR_LLM_CONTEXT_LEN      AGENTOS_ERR_LLM_CONTEXT_LEN
#define AGENTOS_ERROR_LLM_INVALID_MODEL    AGENTOS_ERR_LLM_INVALID_MODEL
#define AGENTOS_ERROR_LLM_AUTH_FAIL        AGENTOS_ERR_LLM_AUTH_FAIL

/* 工具服务错误码兼容 */
#define AGENTOS_ERROR_TOOL_BASE            AGENTOS_ERR_EXEC_BASE
#define AGENTOS_ERROR_TOOL_NOT_FOUND       AGENTOS_ERR_EXEC_NOT_FOUND
#define AGENTOS_ERROR_TOOL_EXEC_FAIL       AGENTOS_ERR_EXEC_FAIL
#define AGENTOS_ERROR_TOOL_TIMEOUT         AGENTOS_ERR_EXEC_TIMEOUT
#define AGENTOS_ERROR_TOOL_VALIDATION      AGENTOS_ERR_EXEC_VALIDATION
#define AGENTOS_ERROR_TOOL_SANDBOX         AGENTOS_ERR_EXEC_SANDBOX

/* 调度服务错误码兼容 */
#define AGENTOS_ERROR_SCHED_BASE           AGENTOS_ERR_KERN_BASE
#define AGENTOS_ERROR_SCHED_NO_AGENT       AGENTOS_ERR_KERN_SCHED
#define AGENTOS_ERROR_SCHED_AGENT_BUSY     AGENTOS_ERR_SVC_BUSY
#define AGENTOS_ERROR_SCHED_STRATEGY       AGENTOS_ERR_KERN_SCHED
#define AGENTOS_ERROR_SCHED_AGENT_NOT_FOUND AGENTOS_ERR_NOT_FOUND
#define AGENTOS_ERROR_SCHED_NO_AVAILABLE   AGENTOS_ERR_KERN_SCHED

/* 市场服务错误码兼容 */
#define AGENTOS_ERROR_MARKET_BASE          AGENTOS_ERR_SVC_BASE
#define AGENTOS_ERROR_MARKET_NOT_FOUND     AGENTOS_ERR_NOT_FOUND
#define AGENTOS_ERROR_MARKET_INSTALL       AGENTOS_ERR_EXEC_FAIL
#define AGENTOS_ERROR_MARKET_DEPENDENCY    AGENTOS_ERR_SVC_DEPENDENCY

/* 监控服务错误码兼容 */
#define AGENTOS_ERROR_MONITOR_BASE         AGENTOS_ERR_SVC_BASE
#define AGENTOS_ERROR_MONITOR_METRIC       AGENTOS_ERR_SYS_RESOURCE
#define AGENTOS_ERROR_MONITOR_TRACE        AGENTOS_ERR_SYS_RESOURCE
#define AGENTOS_ERROR_MONITOR_ALERT        AGENTOS_ERR_SYS_RESOURCE

/* Daemon 服务层错误码（commons 未定义，daemon 模块扩展） */
#ifndef AGENTOS_ERR_DAEMON_BASE
#define AGENTOS_ERR_DAEMON_BASE            (-600)
#endif
#define AGENTOS_ERR_DAEMON_AUTH_FAIL      (AGENTOS_ERR_DAEMON_BASE + 0x01)
#define AGENTOS_ERR_DAEMON_CONFIG_INVALID (AGENTOS_ERR_DAEMON_BASE + 0x02)
#define AGENTOS_ERR_DAEMON_INIT_FAILED    (AGENTOS_ERR_DAEMON_BASE + 0x03)
#define AGENTOS_ERR_DAEMON_ALREADY_INIT   (AGENTOS_ERR_DAEMON_BASE + 0x04)

/* Daemon 层兼容别名 */
#ifndef AGENTOS_ERR_ALREADY_INIT
#define AGENTOS_ERR_ALREADY_INIT          AGENTOS_ERR_DAEMON_ALREADY_INIT
#endif

/* ==================== 兼容性函数别名 ==================== */

/**
 * @brief 兼容旧函数名
 * @deprecated 请使用 agentos_error_str
 */
#define agentos_strerror(code) agentos_error_str(code)

/**
 * @brief 兼容旧函数名
 * @deprecated 请使用 agentos_error_str
 */
#define agentos_error_name(code) agentos_error_str(code)

/* ==================== 兼容性宏 ==================== */

/**
 * @brief 错误码检查宏（兼容旧代码）
 */
#define AGENTOS_IS_ERROR(code)              ((code) != AGENTOS_OK)
#define AGENTOS_IS_SUCCESS(code)            ((code) == AGENTOS_OK)

/* ==================== 兼容性类型别名 ==================== */

#endif /* AGENTOS_DAEMON_COMMON_ERROR_H */
