#ifndef AGENTOS_TASKFLOW_VERSION_H
#define AGENTOS_TASKFLOW_VERSION_H

#define TASKFLOW_VERSION_MAJOR 
#define TASKFLOW_VERSION_MINOR 
#define TASKFLOW_VERSION_PATCH 
#define TASKFLOW_VERSION ""

#endif
